// tauri-app/src/components/VoiceSettingsPanel.tsx
import { useEffect, useRef, useState } from 'react';
import { useAppStore } from '../store/useAppStore';
import { VoiceSelector } from './VoiceSelector';
import { t } from '../locales';

interface VoiceSettingsPanelProps {
  isVisible: boolean;
  onClose: () => void;
  isSelectorOpen: boolean;
  setIsSelectorOpen: (open: boolean) => void;
}

export function VoiceSettingsPanel({
  isVisible,
  onClose,
  isSelectorOpen,
  setIsSelectorOpen
}: VoiceSettingsPanelProps) {
  const { currentVoice, setCurrentVoice, audioConfig, setAudioConfig } = useAppStore();
  const panelRef = useRef<HTMLDivElement>(null);
  const [localConfig, setLocalConfig] = useState({
    speed: audioConfig.speed,
    pitch: audioConfig.pitch,
    volume: audioConfig.volume
  });

  useEffect(() => {
    setLocalConfig({
      speed: audioConfig.speed,
      pitch: audioConfig.pitch,
      volume: audioConfig.volume
    });
  }, [audioConfig]);

  const handleSpeedChange = (speed: number) => {
    const newConfig = { ...localConfig, speed };
    setLocalConfig(newConfig);
    setAudioConfig(newConfig);
    setCurrentVoice({ ...currentVoice, speed });
  };

  const handleVolumeChange = (volume: number) => {
    const normalizedVolume = volume / 10;
    const newConfig = { ...localConfig, volume: normalizedVolume };
    setLocalConfig(newConfig);
    setAudioConfig(newConfig);
    setCurrentVoice({ ...currentVoice, volume: normalizedVolume });
  };

  const handlePitchChange = (pitch: number) => {
    const normalizedPitch = 0.5 + (pitch / 10) * 1.5;
    const newConfig = { ...localConfig, pitch: normalizedPitch };
    setLocalConfig(newConfig);
    setAudioConfig(newConfig);
    setCurrentVoice({ ...currentVoice, pitch: normalizedPitch });
  };

  if (!isVisible) return null;

  return (
    <>
      <div
        ref={panelRef}
        className="absolute top-[calc(100%-1px)] left-0 w-full bg-gradient-to-r from-orange-50 to-rose-50 rounded-b-[16px] shadow-md shadow-orange-100 border-l border-r border-b border-orange-200 z-50 px-3 py-2 max-h-[200px] overflow-y-auto"
        onMouseEnter={() => undefined}
        onMouseLeave={onClose}
      >
        <div className="grid grid-rows-3 gap-0">
        <div className="flex flex-col justify-center border-b border-orange-100/80 pb-1.5">
          <div className="flex items-center justify-between gap-2 mb-0.5">
            <div className="text-[15px] font-medium text-slate-800">{t('voice.speed')}:</div>
            <div className="text-[15px] font-medium text-slate-700">{localConfig.speed.toFixed(1)}x</div>
          </div>
          <input
            type="range"
            min="0.5"
            max="2.0"
            step="0.1"
            value={localConfig.speed}
            onChange={(e) => handleSpeedChange(parseFloat(e.target.value))}
            className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-orange-500"
            style={{
              background: `linear-gradient(to right, #fb923c 0%, #fb923c ${((localConfig.speed - 0.5) / 1.5) * 100}%, #e5e7eb ${((localConfig.speed - 0.5) / 1.5) * 100}%, #e5e7eb 100%)`
            }}
          />
        </div>

        <div className="flex flex-col justify-center border-b border-orange-100/80 py-1.5">
          <div className="mb-0.5 text-[15px] font-medium text-slate-800">{t('voice.volume')}</div>
          <div className="flex items-center gap-2.5">
            <span className="text-[13px] text-slate-500 w-4 flex-shrink-0">{t('voice.small')}</span>
            <input
              type="range"
              min="0"
              max="10"
              step="1"
              value={Math.round(localConfig.volume * 10)}
              onChange={(e) => handleVolumeChange(parseInt(e.target.value))}
              className="flex-1 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-orange-500"
              style={{
                background: `linear-gradient(to right, #fb923c 0%, #fb923c ${localConfig.volume * 100}%, #e5e7eb ${localConfig.volume * 100}%, #e5e7eb 100%)`
              }}
            />
            <span className="text-[13px] text-slate-500 w-4 flex-shrink-0">{t('voice.large')}</span>
          </div>
          <div className="mt-0.5 text-center text-[15px] font-medium text-slate-700">{Math.round(localConfig.volume * 10)}</div>
        </div>

        <div className="flex flex-col justify-center pt-1.5">
          <div className="mb-0.5 text-[15px] font-medium text-slate-800">{t('voice.pitch')}</div>
          <div className="flex items-center gap-2.5">
            <span className="text-[13px] text-slate-500 w-4 flex-shrink-0">{t('voice.low')}</span>
            <input
              type="range"
              min="0"
              max="10"
              step="1"
              value={Math.round(((localConfig.pitch - 0.5) / 1.5) * 10)}
              onChange={(e) => handlePitchChange(parseInt(e.target.value))}
              className="flex-1 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-orange-500"
              style={{
                background: `linear-gradient(to right, #fb923c 0%, #fb923c ${((localConfig.pitch - 0.5) / 1.5) * 100}%, #e5e7eb ${((localConfig.pitch - 0.5) / 1.5) * 100}%, #e5e7eb 100%)`
              }}
            />
            <span className="text-[13px] text-slate-500 w-4 flex-shrink-0">{t('voice.high')}</span>
          </div>
          <div className="mt-0.5 text-center text-[15px] font-medium text-slate-700">
            {Math.round(((localConfig.pitch - 0.5) / 1.5) * 10)}
          </div>
        </div>
        </div>
      </div>

      <VoiceSelector
        isOpen={isSelectorOpen}
        onClose={() => setIsSelectorOpen(false)}
      />
    </>
  );
}

// web/src/components/VoiceSettingsPanel.vue
<template>
  <div class="settings-panel">
    <div class="setting-block">
      <div class="setting-head">
        <span class="setting-title">{{ t('voice.speed') }}</span>
        <span class="setting-inline">{{ audioConfig.speed.toFixed(1) }}x</span>
      </div>
      <input v-model.number="speedValue" class="slider" type="range" min="0.5" max="2" step="0.1" />
    </div>

    <div class="setting-block">
      <div class="setting-head">
        <span class="setting-title">{{ t('voice.volume') }}</span>
      </div>
      <div class="slider-row">
        <span>{{ t('voice.small') }}</span>
        <input v-model.number="volumeValue" class="slider" type="range" min="0" max="2" step="0.1" />
        <span>{{ t('voice.large') }}</span>
      </div>
      <div class="setting-value">{{ Math.round(audioConfig.volume * 10) }}</div>
    </div>

    <div class="setting-block setting-block--last">
      <div class="setting-head">
        <span class="setting-title">{{ t('voice.pitch') }}</span>
      </div>
      <div class="slider-row">
        <span>{{ t('voice.low') }}</span>
        <input v-model.number="pitchStep" class="slider" type="range" min="0" max="10" step="1" />
        <span>{{ t('voice.high') }}</span>
      </div>
      <div class="setting-value">{{ pitchStep }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { useAppStore } from '../stores/appStore';

const appStore = useAppStore();
const { t } = useI18n();
const audioConfig = computed(() => appStore.audioConfig);

const speedValue = computed({
  get: () => appStore.audioConfig.speed,
  set: (value: number) => appStore.setAudioConfig({ speed: value }),
});

const volumeValue = computed({
  get: () => appStore.audioConfig.volume,
  set: (value: number) => appStore.setAudioConfig({ volume: value }),
});

const pitchStep = computed({
  get: () => Math.round(((appStore.audioConfig.pitch - 0.5) / 1.5) * 10),
  set: (value: number) => {
    const normalized = Math.max(0, Math.min(10, Number(value) || 0));
    appStore.setAudioConfig({ pitch: 0.5 + (normalized / 10) * 1.5 });
  },
});
</script>

<style scoped>
/* 与 VoiceEditor .text-editor min-height:420px 对齐，展开区约为输入区一半高度 */
.settings-panel {
  width: 100%;
  max-height: 210px;
  padding: 0 12px 10px;
  border: 1px solid #ffd2b0;
  border-top: none;
  border-radius: 0 0 18px 18px;
  background: linear-gradient(180deg, rgba(255, 248, 243, 0.98), rgba(255, 244, 236, 0.94));
  box-sizing: border-box;
  display: grid;
  grid-template-rows: repeat(3, auto);
  gap: 2px;
  overflow-y: auto;
}

.setting-block {
  display: flex;
  flex-direction: column;
  justify-content: center;
  min-height: 0;
  border-top: 1px solid rgba(251, 146, 60, 0.2);
}

.setting-block:first-child {
  border-top: none;
}

.setting-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 4px;
}

.setting-title,
.setting-inline,
.setting-value,
.slider-row {
  color: #334155;
}

.setting-title,
.setting-inline {
  font-size: 12px;
}

.setting-title {
  font-weight: 600;
}

.slider-row {
  display: grid;
  grid-template-columns: minmax(46px, auto) 1fr minmax(46px, auto);
  align-items: center;
  gap: 8px;
  font-size: 11px;
}

.slider-row > span {
  min-width: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.slider-row > span:first-child {
  text-align: left;
}

.slider-row > span:last-child {
  text-align: right;
}

.setting-value {
  margin-top: 2px;
  text-align: center;
  font-size: 11px;
  line-height: 1.2;
}

.slider {
  width: 100%;
  height: 12px;
  accent-color: #ff7a1a;
}
</style>
